---
##app wide settings
:app_title: "Area 51"
:app_subtitle: "A semi-original comic"
:app_author: "Area Fifty-One"
:app_description: "Just a simple webcomic"
:log_level: DEBUG

## production db setup
:db_user: "afo"
:db_password: "changeme"
:db_path: "localhost/afo"

## privileged access
:admins:
  - :name: "jarda"
    :password: "changeme"

  - :name: "martin"
    :password: "changeme"

  - :name: "ondra"
    :password: "changeme"
